#!/bin/bash

source ~/.my_colors.sh

temperature=$(sensors | grep 'CPU' | awk -F '[+°]' '{print $2}')

formatted_temperature=$(echo "$temperature" | awk '{
    printf "%.0f", $1 
}')

if [ "$formatted_temperature" -le 50 ]; then
        color=$MY_GREEN
elif [[ "$formatted_temperature" -gt 50 && "$formatted_temperature" -le 60 ]]; then
        color=$MY_YELLOW
elif [[ "$formatted_temperature" -gt 60 && "$formatted_temperature" -le 70 ]]; then
        color=$MY_ORANGE
else
        color=$MY_RED
fi

echo "<span size='large'>󰟀 </span><span color=\"$color\">$formatted_temperature°C </span><span color=\"$color\" size='large'></span>"
