#!/bin/bash

source ~/.my_colors.sh

# This script gets the number of available Flatpak updates
updates=$(flatpak remote-ls --updates --columns=application | wc -l)

if [ "$updates" -eq 0 ]; then
	color=$MY_GREEN
elif [[ "$updates" -gt 0 && "$updates" -le 2 ]]; then
	color=$MY_YELLOW
elif [[ "$updates" -gt 2 && "$updates" -le 3 ]]; then
	color=$MY_ORANGE
else
	color=$MY_RED
fi

printf -v padded_output "%3s" "$updates"

echo "<span color=\"$color\">$padded_output </span><span color=\"$color\" size='large'></span>"
