#!/bin/bash

source ~/.my_colors.sh

# 1. Capture raw sensors data once
sensors_raw=$(sensors)

fan_speed=$(echo "$sensors_raw" | grep "fan2:" | awk -F: '{print $2}' | awk '{print $1}')

if [[ -z "$fan_speed" ]]; then
    fan_speed="ERR"
fi

if [ "$fan_speed" -le 800 ]; then
    color=$MY_GREEN
elif [[ "$fan_speed" -gt 800 && "$fan_speed" -le 1600 ]]; then
    color=$MY_YELLOW
elif [[ "$fan_speed" -gt 1600 && "$fan_speed" -le 2400 ]]; then
    color=$MY_ORANGE
else
    color=$MY_RED
fi

# Force the output to include expected digits
printf -v padded_output "%04d" "$fan_speed"

echo "<span color=\"$color\">$padded_output </span><span color=\"$color\" size='large'>󰈐</span>"