#!/bin/bash

source ~/.my_colors.sh

# Hide block if no nvidia gpu
command -v nvidia-smi >/dev/null 2>&1 || exit 0

# Usage, Temperature, Fan Speed
gpu_data=$(nvidia-smi --query-gpu=utilization.gpu,temperature.gpu,fan.speed --format=csv,noheader,nounits 2>/dev/null)
[[ -z "$gpu_data" ]] && exit 0
IFS=', ' read -r usage temperature fan_speed <<< "$gpu_data"

# Make sure all values are numbers
is_num() { [[ "$1" =~ ^[0-9]+$ ]]; }


if ! is_num "$usage"; then
        usage_color=$MY_RED
else
        formatted_usage="${usage}%"
        if [ "$usage" -le 50 ]; then
                usage_color=$MY_GREEN
        elif [ "$usage" -le 70 ]; then
                usage_color=$MY_YELLOW
        elif [ "$usage" -le 85 ]; then
                usage_color=$MY_ORANGE
        elif [ "$usage" -gt 99 ]; then
                formatted_usage=""
                usage_color=$MY_RED
        else
                formatted_usage="ERR"
                usage_color=$MY_RED
        fi
fi

if ! is_num "$temperature"; then
        temp_color=$MY_RED
else
        if [ "$temperature" -le 50 ]; then
                temp_color=$MY_GREEN
        elif [ "$temperature" -le 60 ]; then
                temp_color=$MY_YELLOW
        elif [ "$temperature" -le 70 ]; then
                temp_color=$MY_ORANGE
        else
                temp_color=$MY_RED
        fi
fi

if ! is_num "$fan_speed"; then
    fan_color=$MY_RED
    padded_fan_speed="ERR "
else
    printf -v padded_fan_speed "%04d" "$fan_speed"
    if [ "$fan_speed" -le 800 ]; then
        fan_color=$MY_GREEN
    elif [ "$fan_speed" -le 1600 ]; then
        fan_color=$MY_YELLOW
    elif [ "$fan_speed" -le 2400 ]; then
        fan_color=$MY_ORANGE
    else
        fan_color=$MY_RED
    fi
fi

printf -v padded_usage "%3s" "$formatted_usage"

echo "<span color=\"$fan_color\">$padded_fan_speed </span><span color=\"$fan_color\" size='large'>󰈐</span> - <span color=\"$usage_color\" size='large'>󰓅</span><span color=\"$usage_color\"> $padded_usage</span><span size='large'> 󰖺 </span><span color=\"$temp_color\">$temperature°C </span><span color=\"$temp_color\" size='large'></span>"