#!/bin/bash

source ~/.my_colors.sh

RAM_PERCENT=$(awk '/MemTotal/ {T=$2} /MemAvailable/ {A=$2} END {printf "%.0f", (T-A)/T*100}' /proc/meminfo)

if [ "$RAM_PERCENT" -le 50 ]; then
	color=$MY_GREEN
elif [[ "$RAM_PERCENT" -gt 50 && "$RAM_PERCENT" -le 70 ]]; then
	color=$MY_YELLOW
elif [[ "$RAM_PERCENT" -gt 70 && "$RAM_PERCENT" -le 85 ]]; then
	color=$MY_ORANGE
else
	color=$MY_RED
fi

printf -v padded_output "%3s" "$RAM_PERCENT"

echo "<span color=\"$color\">${padded_output}% </span><span color=\"$color\" size='large'>󰧑</span>"
