#!/bin/bash

STATUS=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)

if echo "$STATUS" | grep -q '\[MUTED\]'; then
    volume="MUTE"
    icon=" 󰖁"
else
    VOLUME_PERCENT=$(echo "$STATUS" | awk '/Volume/ {printf "%.0f", $2 * 100}')
    volume="${VOLUME_PERCENT}%"
    if [ "$VOLUME_PERCENT" -le 50 ]; then
	icon=" 󰖀"
    elif [ "$VOLUME_PERCENT" -gt 100 ]; then
	volume="100%"
	icon=" 󰕾"
    else 
	icon=" 󰕾"
    fi 
fi

if [ ${#volume} -eq 2 ]; then
    padded_output="__$volume"   # Add one underscore for double digits
elif [ ${#volume} -eq 3 ]; then
    padded_output="_$volume"   # Add one underscore for double digits
else
    padded_output="$volume"    # Leave 3-digit speeds alone
fi


echo "$padded_output<span size='large'>$icon</span>"