#!/bin/bash

source ~/.my_colors.sh

# CPU Usage
CPU_USAGE=$(top -bn1 | grep "Cpu(s)" | awk '{printf "%.0f", 100 - $8}')
OUTPUT_VALUE=${CPU_USAGE}%

if [ "$CPU_USAGE" -le 50 ]; then
        usage_color=$MY_GREEN
elif [[ "$CPU_USAGE" -gt 50 && "$CPU_USAGE" -le 70 ]]; then
        usage_color=$MY_YELLOW
elif [[ "$CPU_USAGE" -gt 70 && "$CPU_USAGE" -le 85 ]]; then
        usage_color=$MY_ORANGE
elif [[ "$CPU_USAGE" -gt 85 && "$CPU_USAGE" -le 99 ]]; then
        usage_color=$MY_RED
elif [ "$CPU_USAGE" -gt 99 ]; then
        OUTPUT_VALUE=""
else
        OUTPUT_VALUE="ERR"
        usage_color=$MY_RED
fi

# CPU Temperature and Fan Speed
cpu_script_dir=$(dirname -- "${BASH_SOURCE[0]}")
read -r formatted_temperature fan_speed < <("$cpu_script_dir/thermal")

if [ "$formatted_temperature" -le 50 ]; then
        temp_color=$MY_GREEN
elif [[ "$formatted_temperature" -gt 50 && "$formatted_temperature" -le 60 ]]; then
        temp_color=$MY_YELLOW
elif [[ "$formatted_temperature" -gt 60 && "$formatted_temperature" -le 70 ]]; then
        temp_color=$MY_ORANGE
else
        temp_color=$MY_RED
fi

if [ "$fan_speed" -le 800 ]; then
    fan_color=$MY_GREEN
elif [[ "$fan_speed" -gt 800 && "$fan_speed" -le 1600 ]]; then
    fan_color=$MY_YELLOW
elif [[ "$fan_speed" -gt 1600 && "$fan_speed" -le 2400 ]]; then
    fan_color=$MY_ORANGE
else
    fan_color=$MY_RED
fi

printf -v padded_usage "%3s" "$OUTPUT_VALUE"
printf -v padded_fan_speed "%04d" "$fan_speed" 

echo "<span color=\"$fan_color\">$padded_fan_speed </span><span color=\"$fan_color\" size='large'>󰈐</span> - <span color=\"$usage_color\" size='large'>󰓅</span><span color=\"$usage_color\"> $padded_usage</span><span size='large'> 󰟀 </span><span color=\"$temp_color\">$formatted_temperature°C </span><span color=\"$temp_color\" size='large'></span>"